Add CeloDance Wallet to Celo use-contractkit
celo-tools/use-contractkit pull request #33
Opened 2021-09-07 09:33 UTC by 1035569003

as a celo mobile wallet, celodance support the transfer and staking of celo assets. after talking with clabs and moola, we propose to integrate celodance wallet to moola. the development work is all finished, so please merge the code, thanks!

2021-09-08 14:27 UTC, jmrossy requested changes
Thanks for the PR! Please see the comments below

2021-09-08 14:27 UTC, jmrossy commented on yarn.lock
> +"@celo-tools/use-contractkit@1.1.0":
Why has the yarn.lock file changed?

2021-09-08 14:27 UTC, jmrossy commented on packages/use-contractkit/src/constants.tsx
> +      'Send、Vote and Earn rewards within one wallet',
I think you've used the wrong character here for the `,` after 'Send'.
Also please change the casing to 'Send, vote, and earn'

2021-09-08 14:27 UTC, jmrossy commented on packages/use-contractkit/src/constants.tsx
> +    listPriority: () => 0,
Please set this to 1

2021-09-08 14:27 UTC, jmrossy commented on packages/use-contractkit/src/walletIcons.tsx
> +
please clean up the spacing

2021-09-08 14:27 UTC, jmrossy commented on packages/use-contractkit/src/walletIcons.tsx
> +export const CELODANCE: React.FC<React.SVGProps<SVGSVGElement>> = (
rename to CELO_DANCE

2021-09-08 14:27 UTC, jmrossy commented on packages/use-contractkit/src/connectors/connectors.ts
> +export class CeloDanceConnector implements Connector {
Why have you created a new connector? It seems to be just a copy of another connector

2021-09-08 14:29 UTC, jmrossy commented
@1035569003 In addition to the changes I requested, we'll need to chat with you briefly on Discord before we accept code changes. Your Github account is brand new and has no name. It simply looks too suspicious.

2021-09-09 02:30 UTC, bi23com commented
> @1035569003 In addition to the changes I requested, we'll need to chat with you briefly on Discord before we accept code changes. Your Github account is brand new and has no name. It simply looks too suspicious.

hi，it's our new developer and he use his new account. sure please contact us in discord, the handle is  Emma | Bi23 Labs#9980.  thank you very much!

2021-09-14 10:24 UTC, closed without merging